# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tmp.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1320, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 161, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.colorButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons for editor/Icons8-Windows-8-Diy-Paint-Brush.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorButton.setIcon(icon)
        self.colorButton.setCheckable(True)
        self.colorButton.setAutoExclusive(True)
        self.colorButton.setObjectName("colorButton")
        self.gridLayout_2.addWidget(self.colorButton, 0, 0, 1, 1)
        self.maskButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons for editor/mask_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maskButton.setIcon(icon1)
        self.maskButton.setCheckable(True)
        self.maskButton.setAutoExclusive(True)
        self.maskButton.setObjectName("maskButton")
        self.gridLayout_2.addWidget(self.maskButton, 0, 1, 1, 1)
        self.undoButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons for editor/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoButton.setIcon(icon2)
        self.undoButton.setCheckable(False)
        self.undoButton.setAutoExclusive(False)
        self.undoButton.setObjectName("undoButton")
        self.gridLayout_2.addWidget(self.undoButton, 0, 3, 1, 1)
        self.sketchButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons for editor/pencil-copy-1411473188gk8n4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sketchButton.setIcon(icon3)
        self.sketchButton.setCheckable(True)
        self.sketchButton.setAutoExclusive(True)
        self.sketchButton.setObjectName("sketchButton")
        self.gridLayout_2.addWidget(self.sketchButton, 0, 2, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(200, 20, 512, 512))
        self.graphicsView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(789, 20, 512, 512))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 60, 161, 171))
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.maskSizeSlider = QtWidgets.QSlider(self.page)
        self.maskSizeSlider.setGeometry(QtCore.QRect(10, 30, 91, 22))
        self.maskSizeSlider.setMinimum(1)
        self.maskSizeSlider.setMaximum(100)
        self.maskSizeSlider.setProperty("value", 12)
        self.maskSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.maskSizeSlider.setObjectName("maskSizeSlider")
        self.maskSizeLabel = QtWidgets.QLabel(self.page)
        self.maskSizeLabel.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.maskSizeLabel.setObjectName("maskSizeLabel")
        self.maskSpinBox = QtWidgets.QSpinBox(self.page)
        self.maskSpinBox.setGeometry(QtCore.QRect(110, 30, 41, 24))
        self.maskSpinBox.setMinimum(1)
        self.maskSpinBox.setMaximum(100)
        self.maskSpinBox.setProperty("value", 12)
        self.maskSpinBox.setObjectName("maskSpinBox")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.sketchSizeLabel = QtWidgets.QLabel(self.page_3)
        self.sketchSizeLabel.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.sketchSizeLabel.setObjectName("sketchSizeLabel")
        self.sketchSpinBox = QtWidgets.QSpinBox(self.page_3)
        self.sketchSpinBox.setGeometry(QtCore.QRect(110, 30, 41, 24))
        self.sketchSpinBox.setMinimum(1)
        self.sketchSpinBox.setMaximum(100)
        self.sketchSpinBox.setProperty("value", 2)
        self.sketchSpinBox.setObjectName("sketchSpinBox")
        self.sketchSizeSlider = QtWidgets.QSlider(self.page_3)
        self.sketchSizeSlider.setGeometry(QtCore.QRect(10, 30, 91, 22))
        self.sketchSizeSlider.setMinimum(1)
        self.sketchSizeSlider.setMaximum(100)
        self.sketchSizeSlider.setProperty("value", 2)
        self.sketchSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sketchSizeSlider.setObjectName("sketchSizeSlider")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.paintSpinBox = QtWidgets.QSpinBox(self.page_2)
        self.paintSpinBox.setGeometry(QtCore.QRect(110, 30, 41, 24))
        self.paintSpinBox.setMinimum(1)
        self.paintSpinBox.setMaximum(100)
        self.paintSpinBox.setProperty("value", 8)
        self.paintSpinBox.setObjectName("paintSpinBox")
        self.paintSizeLabel = QtWidgets.QLabel(self.page_2)
        self.paintSizeLabel.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.paintSizeLabel.setObjectName("paintSizeLabel")
        self.paintSizeSlider = QtWidgets.QSlider(self.page_2)
        self.paintSizeSlider.setGeometry(QtCore.QRect(10, 30, 91, 22))
        self.paintSizeSlider.setMinimum(1)
        self.paintSizeSlider.setMaximum(100)
        self.paintSizeSlider.setProperty("value", 8)
        self.paintSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.paintSizeSlider.setObjectName("paintSizeSlider")
        self.colorSelectButton = QtWidgets.QPushButton(self.page_2)
        self.colorSelectButton.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.colorSelectButton.setObjectName("colorSelectButton")
        self.stackedWidget.addWidget(self.page_2)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(720, 220, 61, 61))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons for editor/ai-82-839583.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon4)
        self.toolButton.setIconSize(QtCore.QSize(40, 40))
        self.toolButton.setObjectName("toolButton")
        self.stackedWidget.raise_()
        self.verticalLayoutWidget.raise_()
        self.graphicsView.raise_()
        self.graphicsView_2.raise_()
        self.toolButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1320, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClear_Image = QtWidgets.QAction(MainWindow)
        self.actionClear_Image.setObjectName("actionClear_Image")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClear_Image)
        self.menubar.addAction(self.menuFile.menuAction())

        self.actionOpen.triggered.connect(MainWindow.open)
        self.actionSave.triggered.connect(MainWindow.save_img)
        self.undoButton.clicked.connect(MainWindow.undo)
        self.actionClear_Image.triggered.connect(MainWindow.clear)
        self.sketchButton.clicked.connect(MainWindow.sketch_mode)
        self.colorButton.clicked.connect(MainWindow.stroke_mode)
        self.maskButton.clicked.connect(MainWindow.mask_mode)
        self.toolButton.clicked.connect(MainWindow.complete)
        self.colorSelectButton.clicked.connect(MainWindow.color_change_mode)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.maskSizeSlider.sliderMoved['int'].connect(self.maskSpinBox.setValue)
        self.maskSpinBox.valueChanged['int'].connect(self.maskSizeSlider.setValue)
        self.sketchSizeSlider.valueChanged['int'].connect(self.sketchSpinBox.setValue)
        self.sketchSpinBox.valueChanged['int'].connect(self.sketchSizeSlider.setValue)
        self.paintSizeSlider.valueChanged['int'].connect(self.paintSpinBox.setValue)
        self.paintSpinBox.valueChanged['int'].connect(self.paintSizeSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.colorButton.setToolTip(_translate("MainWindow", "Paint Color"))
        self.colorButton.setText(_translate("MainWindow", "..."))
        self.maskButton.setToolTip(_translate("MainWindow", "Masking"))
        self.maskButton.setText(_translate("MainWindow", "..."))
        self.undoButton.setToolTip(_translate("MainWindow", "Erase"))
        self.undoButton.setText(_translate("MainWindow", "..."))
        self.sketchButton.setToolTip(_translate("MainWindow", "Sketch"))
        self.sketchButton.setText(_translate("MainWindow", "..."))
        self.maskSizeLabel.setText(_translate("MainWindow", "Mask Size"))
        self.sketchSizeLabel.setText(_translate("MainWindow", "Sketch Size"))
        self.paintSizeLabel.setText(_translate("MainWindow", "Paint Size"))
        self.colorSelectButton.setText(_translate("MainWindow", "Color"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open Image"))
        self.actionSave.setText(_translate("MainWindow", "Save Image"))
        self.actionClear_Image.setText(_translate("MainWindow", "Clear Image"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))


if __name__ == '__main__':
    config = Config('demo.yaml')
    os.environ["CUDA_VISIBLE_DEVICES"] = str(config.GPU_NUM)
    model = Model(config)

    app = QApplication(sys.argv)
    ex = Ex(model, config)
    sys.exit(app.exec_())
